title: "The BioHub"
description: "Supporting the Bioindustrial Manufacturing Community in Central Massachusetts"
url: "https://massbiohub.org"
baseurl: ""

markdown: kramdown
permalink: pretty
plugins: []