title: "The BioHub"
description: "Supporting the Bioindustrial Manufacturing Community in Central Massachusetts"
url: ""
baseurl: ""   # set to "/repo-name" if using username.github.io/repo-name

markdown: kramdown
permalink: pretty
plugins: []