title: "The BioHub"
description: "Supporting the Bioindustrial Manufacturing Community in Central Massachusetts"
url: "https://yoeric.github.io"
baseurl: "/mass_biohub"

markdown: kramdown
permalink: pretty
plugins: []